project:
  type: website
  output-dir: docs

website:
  title: "ProjectSEE"
  navbar:
    search: false
    logo: Figures/logo_espol.png
    background: dark
    tools:
      - icon: twitter
        href: https://twitter.com/whosleonardom
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Leon2602/ProjectQuarto
          - text: Report a Bug
            href:  https://github.com/Leon2602/ProjectQuarto/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
  sidebar:
    style: "docked"
    alignment: "center"
    background: light
    contents:
      - section: "Preliminar"
        contents:
          - title: "Notación"
            file: Notation.qmd
          - title: "Teoremas Importantes"
            file: Teo.qmd
      - section: "Espacios de Sobolev"
        contents:
          - title: "Derivada Débil"
            file: WeakDerivate.qmd
          - title: "Espacio de Sobolev"
            file: SobolevSpace.qmd
          - title: "Teorema del Embebimiento de Sobolev"
            file: SobolevEmbeb.qmd
          - title: "Aproximación mediante Funciones Suaves"
            file: SobolevAprox.qmd
          - title: "Espacios de Hölder"
            file: HolderSpace.qmd




format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

      



