project:
  type: website
  output-dir: docs

website:
  title: "ProjectSEE"
  navbar:
    search: false
    logo: Figures/logo_espol.png
    background: dark
    tools:
      - icon: twitter
        href: https://twitter.com/whosleonardom
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/Leon2602/ProjectQuarto
          - text: Report a Bug
            href:  https://github.com/Leon2602/ProjectQuarto/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
  sidebar:
    style: "docked"
    alignment: "center"
    background: light
    contents:
      - section: "Preliminar"
        contents:
          - Notation.qmd
          - Teo.qmd
      - section: "Espacios de Sobolev"
        contents:
          - WeakDerivate.qmd
          - SobolevSpace.qmd
          - SobolevEmbeb.qmd
          - SobolevAprox.qmd
          - HolderSpace.qmd



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

      



