---
title: Una versión simple del teorema de embebimiento de Sobolev
---
::: {.hidden}
$$
\usepackage{amssymb}
\usepackage{amsmath}
\def\R{{\mathbb{R}}}
\def\Z{{\mathbb{Z}}}
\newcommand{\norm}[1]{\left\| #1 \right\|}
\newcommand{\abs}[1]{\left| #1 \right|}
\def\sen{{\textrm{sen}}}
\def\cos{{\textrm{cos}}}
\renewcommand{\qedsymbol}{\blacksquare}
$$
:::


Para dos espacios de Banach $\mathbb{B}_1$ y $\mathbb{B}_2$, decimos que $\mathbb{B}_1$ es embebido (incluido) en $\mathbb{B}_2$ si $\|u\|_{\mathbb{B}_2} \leq C\|u\|_{\mathbb{B}_1}$ para alguna constante $C$ y para $u \in \mathbb{B}_1$. Deseamos determinar qué espacios de Sobolev $W^{k, p}(\Omega)$ pueden ser embebidos en el espacio de funciones continuas. Para motivar el tipo de análisis que se empleará, estudiaremos un caso especial.

:::{.theorembox}

::::{.theorembox-header}
:::::{.theorembox-icon}
:::::
Teorema 3.1 Embebimiento de Sobolev en 2-D
::::

::::{.theorembox-body}

Para $k p \geq 2$,
$$
\max _{x \in \mathbb{R}^2}|u(x)| \leq C\|u\|_{W^{k, p}\left(\mathbb{R}^2\right)} \quad \forall u \in C_0^{\infty}(\Omega) .
$$

::::

:::

*Demostración:*  
Dado $u \in C_0^{\infty}(\Omega)$, demostramos que para todo $x \in \operatorname{supp}(u)$,
    $$
    |u(x)| \leq C\left\|D^\alpha u(x)\right\|_{L^p(\Omega)} \quad \forall|\alpha| \leq k .
    $$
    Al elegir un sistema de coordenadas centrado en $x$, podemos asumir que $x=0$; por lo tanto, basta con demostrar que
    $$
    |u(0)| \leq C\left\|D^\alpha u(x)\right\|_{L^p(\Omega)} \quad \forall|\alpha| \leq k .
    $$
    Sea $g \in C^{\infty}([0, \infty))$ con $0 \leq g \leq 1$, de manera que $g(x)=1$ para $x \in \left[0, \frac{1}{2}\right]$ y $g(x)=0$ para $x \in \left[\frac{3}{4}, \infty\right)$.
    Utilizando el teorema fundamental del cálculo,
    $$
    \begin{aligned}
    u(0) & =-\int_0^1 \partial_r[g(r) u(r, \theta)] d r=-\int_0^1 \partial_r(r) \partial_r[g(r) u(r, \theta)] d r \\
    & =\int_0^1 r \partial_r^2[g(r) u(r, \theta)] d r \\
    & =\frac{(-1)^k}{(k-1) !} \int_0^1 r^{k-1} \partial_r^k[g(r) u(r, \theta)] d r=\frac{(-1)^k}{(k-1) !} \int_0^1 r^{k-2} \partial_r^k[g(r) u(r, \theta)] r d r
    \end{aligned}
    $$
    Al integrar ambos lados de 0 a $2 \pi$, obtenemos que
    $$
    u(0)=\frac{(-1)^k}{2 \pi(k-1) !} \int_0^{2 \pi} \int_0^1 r^{k-2} \partial_r^k[g(r) u(r, \theta)] r d r d \theta .
    $$
    El cambio de variables de coordenadas cartesianas a coordenadas polares es dado por
    $$
    x(r, \theta)=r \cos \theta, \quad y(r, \theta)=r \sin \theta .
    $$
    Mediante la regla de la cadena,
    $$
    \begin{aligned}
    \partial_r u(x(r, \theta), y(r, \theta)) & =\partial_x u \cos \theta+\partial_y u \sin \theta \\
    \partial_r^2 u(x(r, \theta), y(r, \theta)) & =\partial_x^2 u \cos ^2 \theta+2 \partial_{x y}^2 u \cos \theta \sin \theta+\partial_y^2 u \sin ^2 \theta \\
    & \vdots
    \end{aligned}
    $$
    Se sigue que $\partial_r^k=\sum_{|\alpha| \leq k} a_\alpha(\theta) D^\alpha$, donde $a_\alpha$ consiste en polinomios trigonométricos de $\theta$, de manera que
    $$
    \begin{aligned}
    u(0) & =\frac{(-1)^k}{2 \pi(k-1) !} \int_{B(0,1)} r^{k-2} \sum_{|\alpha| \leq k} a_\alpha(\theta) D^\alpha[g(r) u(x)] d x \\
    & \leq C\left\|r^{k-2}\right\|_{L^q(B(0,1))} \sum_{|\alpha| \leq k}\left\|D^\alpha(g u)\right\|_{L^p(B(0,1))} \\
    & \leq C\left(\int_0^1 r^{\frac{p(k-2)}{p-1}} r d r\right)^{\frac{p-1}{p}}\|u\|_{W^{k, p}\left(\mathbb{R}^2\right)} .
    \end{aligned}
    $$
    Por lo tanto, necesitamos $\frac{p(k-2)}{p-1}+1>-1$ o $k p>2$. $\qedsymbol$